apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: leap
  namespace: leap
  labels:
    app: leap

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 128Gi

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: leap
  namespace: leap
  labels:
    app: leap

spec:
  replicas: 1
  selector:
    matchLabels:
      app: leap
  template:
    metadata:
      labels:
        app: leap
    spec:
      containers:
        - name: leap
          image: campsych/leap-platform
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/check/health
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/check/health
              port: 80
            initialDelaySeconds: 300
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: data
          env:
            - name: DB_HOST
              value: "change"
            - name: DB_PASSWORD
              value: "change"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: leap

---

kind: Service
apiVersion: v1

metadata:
  name: leap
  namespace: leap
  labels:
    app: leap

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: leap
