parameters:
    version: "5.0.27"
    available_locales:
        en_GB: english
        zh_CN: 中文
        fr_FR: français
        pl_PL: polski
        tr_TR: türkçe

imports:
    - { resource: parameters.yml }
    - { resource: security.yml } 
    - { resource: parameters_administration.yml }
    - { resource: parameters_test_runner.yml }
    - { resource: parameters_uio.yml }
    - { resource: parameters_saml.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%env(LEAP_PHP_SESSION_SAVE_PATH)%'
        cookie_samesite: 'strict'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: 
        fallback: en_GB

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      env: "%kernel.environment%"
      version: "%version%"
      available_locales: "%available_locales%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: local
        connections:
            local:
                driver:      "%database_driver%"
                server_version: "%env(DB_VERSION)%"
                host:        "%env(DB_HOST)%"
                port:        "%env(DB_PORT)%"
                dbname:      "%env(DB_NAME)%"
                user:        "%env(DB_USER)%"
                password:    "%env(DB_PASSWORD)%"
                charset:     UTF8
                path:        "%database_path%"
                unix_socket: "%database_unix_socket%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

fos_oauth_server:
    db_driver:           orm
    client_class:        Leap\APIBundle\Entity\Client
    access_token_class:  Leap\APIBundle\Entity\AccessToken
    refresh_token_class: Leap\APIBundle\Entity\RefreshToken
    auth_code_class:     Leap\APIBundle\Entity\AuthCode

lexik_jwt_authentication:
    secret_key: "%env(LEAP_JWT_SECRET)%"
    token_ttl: "%env(LEAP_SESSION_TOKEN_EXPIRY_TIME)%"
    encoder:
        signature_algorithm: HS512

scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    google:
        enabled: true
        digits: 6
        window: 1
        #server_name: Server Name
        #issuer: Issuer Name
        template: LeapPanelBundle:Panel:login_mfa.html.twig