imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

services:
    Monolog\Formatter\LogstashFormatter:
         arguments:
            $applicationName: "leap"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            excluded_404s:
                - ^/
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: Monolog\Formatter\LogstashFormatter
        console:
            type: console
            process_psr_3_messages: false
