leap_api:
    resource: "@LeapAPIBundle/Resources/config/routing.yml"
    prefix:   /

leap_panel:
    resource: "@LeapPanelBundle/Resources/config/routing.yml"
    prefix:   /

leap_test:
    resource: "@LeapTestBundle/Resources/config/routing.yml"
    prefix:   /

routing_custom:
    resource: routing_custom.yml

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: LeapPanelBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

2fa_login:
    path: /admin/2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /admin/2fa_check