require(leap5)

ENV_LEAP_R_APP_URL = Sys.getenv("LEAP_R_APP_URL")
ENV_LEAP_R_CLIENT = Sys.getenv("LEAP_R_CLIENT")
ENV_LEAP_R_DB_CONNECTION = Sys.getenv("LEAP_R_DB_CONNECTION")
ENV_LEAP_R_INITIAL_PORT = Sys.getenv("LEAP_R_INITIAL_PORT")
ENV_LEAP_R_MAX_EXEC_TIME = Sys.getenv("LEAP_R_MAX_EXEC_TIME")
ENV_LEAP_R_MAX_IDLE_TIME = Sys.getenv("LEAP_R_MAX_IDLE_TIME")
ENV_LEAP_R_KEEP_ALIVE_TOLERANCE_TIME = Sys.getenv("LEAP_R_KEEP_ALIVE_TOLERANCE_TIME")
ENV_LEAP_R_PLATFORM_URL = Sys.getenv("LEAP_R_PLATFORM_URL")
ENV_LEAP_R_PUBLIC_DIR = Sys.getenv("LEAP_R_PUBLIC_DIR")
ENV_LEAP_R_REDIS_CONNECTION = Sys.getenv("LEAP_R_REDIS_CONNECTION")
ENV_LEAP_R_REQUEST = Sys.getenv("LEAP_R_REQUEST")
ENV_LEAP_R_RUNNER_TYPE = Sys.getenv("LEAP_R_RUNNER_TYPE")
ENV_LEAP_R_SESSION_HASH = Sys.getenv("LEAP_R_SESSION_HASH")
ENV_LEAP_R_SESSION_STORAGE = Sys.getenv("LEAP_R_SESSION_STORAGE")
ENV_LEAP_R_WORKING_DIR = Sys.getenv("LEAP_R_WORKING_DIR")
ENV_LEAP_R_SESSION_FILES_EXPIRATION = Sys.getenv("LEAP_R_SESSION_FILES_EXPIRATION")

leap5:::leap.init(
    dbConnectionParams = fromJSON(ENV_LEAP_R_DB_CONNECTION),
    publicDir = ENV_LEAP_R_PUBLIC_DIR,
    platformUrl = ENV_LEAP_R_PLATFORM_URL,
    appUrl = ENV_LEAP_R_APP_URL,
    maxExecTime = as.numeric(ENV_LEAP_R_MAX_EXEC_TIME),
    maxIdleTime = as.numeric(ENV_LEAP_R_MAX_IDLE_TIME),
    keepAliveToleranceTime = as.numeric(ENV_LEAP_R_KEEP_ALIVE_TOLERANCE_TIME),
    sessionStorage = ENV_LEAP_R_SESSION_STORAGE,
    redisConnectionParams = fromJSON(ENV_LEAP_R_REDIS_CONNECTION),
    sessionFilesExpiration = ENV_LEAP_R_SESSION_FILES_EXPIRATION
)

leap5:::leap.run(
    workingDir = ENV_LEAP_R_WORKING_DIR,
    client = fromJSON(ENV_LEAP_R_CLIENT),
    sessionHash = ENV_LEAP_R_SESSION_HASH,
    initialPort = ENV_LEAP_R_INITIAL_PORT,
    runnerType = ENV_LEAP_R_RUNNER_TYPE,
    response = fromJSON(ENV_LEAP_R_REQUEST)
)