<?php

namespace Leap\APIBundle\Repository;

use Leap\PanelBundle\Repository\AEntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends AEntityRepository
{
}
