version: '2'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    environment:
      - MYSQL_DATABASE=leap
      - MYSQL_USER=leap
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=UTC
    volumes:
      - ./data/mysql:/var/lib/mysql

  leap:
    image: campsych/leap-platform:master
    container_name: leap
    restart: on-failure
    volumes:
      - ./data/leap:/data
    environment:
      - LEAP_PASSWORD=admin
      - LEAP_CONTENT_URL=.
      - LEAP_PLATFORM_URL=/
      - LEAP_GIT_REPOSITORY_PATH=/data/git
      - DB_HOST=database
      - DB_PASSWORD=changeme
      - TZ=UTC
    ports:
      - "80:80"
