version: '2'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    environment:
      - MYSQL_DATABASE=concerto
      - MYSQL_USER=concerto
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=UTC
    volumes:
      - ./data/mysql:/var/lib/mysql

  concerto:
    image: njkookywhiz/leap-platform:master
    container_name: concerto
    restart: on-failure
    volumes:
      - ./data/leap:/data
    environment:
      - CONCERTO_PASSWORD=admin
      - CONCERTO_CONTENT_URL=.
      - CONCERTO_PLATFORM_URL=/
      - CONCERTO_GIT_REPOSITORY_PATH=/data/git
      - DB_HOST=database
      - DB_PASSWORD=changeme
      - TZ=UTC
    ports:
      - "80:80"
